services:
  beebo-api:
    # user: "${USER_PID}:${USER_GID}"
    network_mode: host
    container_name: beebo-api
    env_file: ./beebo_api/.env 
    build:
      context: .
      dockerfile: ./beebo_api/Dockerfile
      args:
          GIT_USER: ${GIT_USER}
          GIT_EMAIL: ${GIT_EMAIL}
    # ports:
    #   - "${AXUM_API_PORT}:${AXUM_API_PORT}"
    restart: unless-stopped
    volumes:
      - ${USER_PROJECT_PATH}/:/api
      # - ${USER_PROJECT_PATH}/beebo_api/beebo_notes:/api/beebo_notes
      - ${HOME}/.ssh/beebo/id_ed25519:/root/.ssh/beebo/id_ed25519:ro
    tty: true
    stdin_open: true
  #
  # beebo_cron:
  #   container_name: beebo-cron
  #   build:
  #     context: .
  #     dockerfile: ./beebo_cron_worker/Dockerfile
  #

